# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-19 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailarchives', '0003_message_resend'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastResentMessage',
            fields=[
                ('sentto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sentat', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='resendmessage',
            unique_together=set([('message', 'sendto')]),
        ),
    ]
