# Generated by Django 5.2.6 on 2025-09-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailarchives", "0004_resend_rate_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listsubscriber",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
